spring:
  datasource:
    url: jdbc:h2:file:./data/demo-db
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}33a94fb73849f169fafcb1a6a896c322eedbc83689a1342690698a7d6bbace38'

token:
  expiration_time: 864000000 # 10days
  # expiration_time: 1000 # 10days
  secret: dev_user_token_user_token_user_token_user_token_user_token_user_token

# gateway: 
#   ip: 192.168.0.8

# server:
  # port: 0 # Random Port

# spring:
#   application:
#     name: user-service
#   h2:
#     console:
#       enabled: true
#       settings:
#         web-allow-others: true
#       path: /h2-console
#   datasource:
#     url: jdbc:h2:file:./data/demo-db
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:
#   jpa:
#     hibernate:
#       ddl-auto: update


